### ISSUE TITLE
`onFinish` should automatically block finish button until await completes

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-vue-wizard#7]

**Comment by gannan08** [comment]
This behavior should exist for all the buttons.

**Comment by gannan08** [comment]
Does this address your concern https://github.com/digitalbazaar/bedrock-vue-wizard/pull/8

**Comment by gannan08** [comment]
Closing issue. The PR has been merged into master and the package has been released (v3.1.0).
